ktor:
  application:
    modules:
      - no.vicx.ktor.ApplicationKt.module
  deployment:
    port: 8080

jwt:
  issuer: "http://localhost:9000/auth-server"
  realm: "ktor sample app"

esport:
  token: "TODO"

user:
  recaptcha:
    secret: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe" # dev secret

postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password