ktor:
  application:
    modules:
      - no.vicx.ApplicationKt.module
  deployment:
    port: 8080

jwt:
  issuer: "http://localhost:9000/auth-server"
  realm: "ktor sample app"

esport:
  token: ""

postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password