import './globals.css'
import {config} from "@fortawesome/fontawesome-svg-core"
import "@fortawesome/fontawesome-svg-core/styles.css"
import {faGithub, faLinkedinIn} from "@fortawesome/free-brands-svg-icons"
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome"
import VicxNavbar from "@/components/VicxNavbar"
import {ReactNode} from "react"

config.autoAddCss = false

export const metadata = {
    title: "Welcome to VICX",
    description: "Generated by Next.js",
}

const RootLayout = ({children}: { children: ReactNode }) => {
    return (
        <html lang="en">
        <body className="min-h-screen flex flex-col bg-gray-100 antialiased">
        <header>
            <VicxNavbar/>
        </header>

        {children}

        <footer className="bg-gray-800 text-white p-4">
            <div className="container mx-auto flex justify-between items-center">
                <p className="text-left">VICX &copy All rights reserved.</p>

                <div className="flex-grow flex justify-center">
                    <div className="flex space-x-4">
                        <a href="#" className="hover:text-yellow-400">
                            <FontAwesomeIcon icon={faLinkedinIn} className="fa-fw"/>
                        </a>
                        <a href="https://github.com/VictorSkinderviken" className="hover:text-yellow-400">
                            <FontAwesomeIcon icon={faGithub} className="fa-fw"/>
                        </a>
                    </div>
                </div>
            </div>
        </footer>
        </body>
        </html>
    )
}

export default RootLayout