import './globals.css'
import {config} from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'

config.autoAddCss = false

import VicxNavbar from "@/components/VicxNavbar"
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome"
import {faGithub, faLinkedinIn} from "@fortawesome/free-brands-svg-icons"

export const metadata = {
    title: 'Welcome to VICX',
    description: 'Generated by Next.js',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className="bg-gray-100 antialiased">

        <div className="flex flex-col min-h-screen">
            <VicxNavbar/>

            <main className="flex-grow">
                {children}
            </main>

            <footer className="bg-gray-800 text-white py-4">
                <div className="container mx-auto flex justify-between items-center">
                    <p className="text-left">VICX &copy All rights reserved.</p>
                    <div className="flex-grow flex justify-center">
                        <div className="flex space-x-4">
                            <a href="#" className="hover:text-yellow-400">
                                <FontAwesomeIcon icon={faLinkedinIn} className="fa-fw"/>
                            </a>
                            <a href="https://github.com/VictorSkinderviken" className="hover:text-yellow-400">
                                <FontAwesomeIcon icon={faGithub} className="fa-fw"/>
                            </a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        </body>
        </html>
    )
}
