name: Build auth-server Docker and push

on:
  push:
    branches:
      - main
    paths:
      - 'auth-server/**'

  pull_request:
    paths:
      - 'auth-server/**'
      - 'gradle/libs.versions.toml'

jobs:
  build-and-push-docker:
    uses: ./.github/workflows/docker-build-template.yml
    secrets: inherit
    with:
      appName: "auth-server"
    permissions:
      contents: read
      packages: write