name: Build python-backend Docker and Push

on:
  push:
    tags:
      - '*'
    paths:
      - 'backend-python/**'
      - 'gradle/libs.versions.toml'

jobs:
  build-and-push-docker:
    uses: ./.github/workflows/docker-build-template.yml
    secrets: inherit
    with:
      moduleName: "backend-python"
      buildWithGradle: false
    permissions:
      contents: read
      packages: write