name: Build backend-ktor Docker and push

on:
  push:
    branches:
      - main
    paths:
      - 'backend-ktor/**'

  pull_request:
    paths:
      - 'backend-ktor/**'
      - 'gradle/libs.versions.toml'

jobs:
  run-tests:
    if: ${{ github.event.pull_request }}
    uses: ./.github/workflows/gradle-run-tests.yml
    secrets: inherit
    with:
      moduleName: "backend-ktor"
    permissions:
      contents: read

  build-and-push-docker:
    if: ${{ !github.event.pull_request }}
    uses: ./.github/workflows/docker-build-template.yml
    secrets: inherit
    with:
      moduleName: "backend-ktor"
    permissions:
      contents: read
      packages: write
